import string

HASH_SIZE = 6
MAX_LENGHT_SHORT = 16
MAX_LENGHT_ORIGINAL = 2000
MAX_ROWS = 10
CHECK_FORMAT = string.ascii_letters + string.digits
PATTERN = f'^[{CHECK_FORMAT}]+'
CUSTOM_ID_FORM_CHECK = f'[{CHECK_FORMAT}]'
