"""empty message

Revision ID: 6ea3662271ba
Revises: 
Create Date: 2022-11-06 13:22:30.671993

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6ea3662271ba"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "URL_map",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("original", sa.String(length=256), nullable=False),
        sa.Column("short", sa.String(length=16), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("original"),
        sa.UniqueConstraint("short"),
    )
    op.create_index(
        op.f("ix_URL_map_timestamp"), "URL_map", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_URL_map_timestamp"), table_name="URL_map")
    op.drop_table("URL_map")
    # ### end Alembic commands ###
